### ISSUE TITLE
Remember Me

### ISSUE THREAD

**Issue by ylynfatt** [relwell/DapsBundle#10]
Does the LdapBundle allow for Symfony's remember-me functionality? I got the following error when I followed the Symfony docs - [How to add "Remember Me" Login Functionality](http://symfony.com/doc/current/cookbook/security/remember_me.html).

> PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'You must configure at least one remember-me aware listener (such as form-login) for each firewall that has remember-me enabled.' in /path/to/my/app/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php:97\nStack trace:\n#0 /path/to/my/app/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php(387): Symfony\Bundle\SecurityBundle\DependencyInjection\Security\Factory\RememberMeFactory->create(Object(Symfony\Component\DependencyInjection\ContainerBuilder), 'main', Array, 'daps_ldap_user_...', NULL)\n#1 /path/to/my/app/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/DependencyInjection/SecurityExtension.php(338): Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension->createAuthenticationListeners(Object(Symfony\Component\DependencyInjection\ContainerBuilder), 'main', Array, Array, 'daps_ldap_user_...')\n#2 /path/to/my/app/vendor/symfony/symfony/src in /path/to/my/app/vendor/symfony/symfony/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/RememberMeFactory.php on line 97,

**Comment by relwell** [comment]
Hi @ylynfatt, not as far as I know. You would probably have to write that logic yourself. It would involve using the admin-driven approach, and then loading the user by name instead of by name and password.
