### ISSUE TITLE
Dependency on non-existent parameters

### ISSUE THREAD

**Issue by ylynfatt** [relwell/DapsBundle#7]
I placed the DapsBundle into my Symfony 2 application's `src` directory and then got the following errors:

```
'The service "daps_ldap.ldap" has a dependency on a non-existent parameter "daps_ldap.ldap.host". Did you mean one of these: "daps_ldap.ldap.admin.host", "daps_ldap.ldap.class"?'
```

and

```
'The service "daps_ldap.ldap" has a dependency on a non-existent parameter "daps_ldap.ldap.admin.username_suffix". Did you mean one of these: "daps_ldap.ldap.admin.enable", "daps_ldap.ldap.admin.username_suffic"?'
```

Here are the full Uncaught Exception messages:

```
[Fri Jun 28 13:02:35 2013] [error] [client 10.0.2.2] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException' with message 'The service "daps_ldap.ldap" has a dependency on a non-existent parameter "daps_ldap.ldap.host". Did you mean one of these: "daps_ldap.ldap.admin.host", "daps_ldap.ldap.class"?' in /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:108\nStack trace:\n#0 /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(234): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get('daps_ldap.ldap....')\n#1 /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(205): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->resolveString('%daps_ldap.ldap...', Array)\n#2 /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(195): Symfony\\Component\\DependencyInjection\\ParameterBag\\Par in /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 108
[Fri Jun 28 13:09:03 2013] [error] [client 10.0.2.2] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ParameterNotFoundException' with message 'The service "daps_ldap.ldap" has a dependency on a non-existent parameter "daps_ldap.ldap.admin.username_suffix". Did you mean one of these: "daps_ldap.ldap.admin.enable", "daps_ldap.ldap.admin.username_suffic"?' in /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:108\nStack trace:\n#0 /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(234): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->get('daps_ldap.ldap....')\n#1 /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(205): Symfony\\Component\\DependencyInjection\\ParameterBag\\ParameterBag->resolveString('%daps_ldap.ldap...', Array)\n#2 /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(195): Symfony\\Component\\D in /vagrant/aces/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 108
```

Are the parameter names in `ldapcredentials.yml` incorrect or are the arguments in `services.xml` incorrect?

**Comment by relwell** [comment]
I include these values in the application config.
